### ISSUE TITLE
ObjectsInstaller: schema "hangfire" does not exist with custom schema name

### ISSUE THREAD

**Issue by alec-anikin** [frankhommers/Hangfire.PostgreSql#110]
https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/Install.v11.sql

All tables in the script are prefixed with schema 'hangfire' but they shouldn't

**Comment by drjameshouse** [comment]
I have also run into this when trying to upgrade ( using the PrepareSchemaIfNecessary = true ) with a different schema name.  It appears the PostgreSqlObjectsInstaller looks to replace hangfire with single and double qoutes 👍 
https://github.com/frankhommers/Hangfire.PostgreSql/blob/04b19881b7c9b8451b0c05d72be8c8bfee3c922b/src/Hangfire.PostgreSql/PostgreSqlObjectsInstaller.cs#L73

However, since the v11 sql script has them without quotes it does not properly replace them.

**Comment by vytautask** [comment]
Thanks for the report! And fix ;)
