### ISSUE TITLE
Hangfire Dashboard Sorting Succeeded and Failed Jobs in a Random Order

### ISSUE THREAD

**Issue by ginadiFFG** [frankhommers/Hangfire.PostgreSql#168]
The Hangfire dashboard is sorting succeeded and failed jobs by ID, because the IDs for Postgres are randomly generated this results the jobs to be sorted in a random order, which makes it difficult to parse and understand which jobs have run.

The jobs should be sorted chronologically by succeeded/failed date to make reading the dashboard easier and more convenient.

**Comment by azygis** [comment]
The IDs are not randomly generated since all of the IDs in this package use [SERIAL](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-SERIAL). Technically there _can_ be some small gaps (see notes in the link), but it's definitely not random.

Since this package is based very much on the Hangfire.SqlServer implementation, and [they use Id as sort order](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/SqlServerMonitoringApi.cs#L545), we'd rather stick to the same ordering, which is ID-based.

Feel free to reopen if there's really a need to change the ordering. For now, since there's not much action in the issue, I'll close it.
