### ISSUE TITLE
TimeSpan.Zero Not Supported for QueuePollInterval

### ISSUE THREAD

**Issue by asadcr** [frankhommers/Hangfire.PostgreSql#229]
The latest hangfire Provider for SQL Server from 1.7.0 supports Zero based Queue Poll Interval.

I would like to know why it's not possible for PostgreSQL
https://github.com/HangfireIO/Hangfire/blob/v1.7.0/src/Hangfire.SqlServer/SqlServerStorageOptions.cs#L60

**Comment by azygis** [comment]
Because it makes no sense and is misleading. It's almost a DoS attack if we are to _really_ use `TimeSpan.Zero` since it would query database repeatedly without any waiting at all.

If you check [SqlServerJobQueue:99](https://github.com/HangfireIO/Hangfire/blob/891369b5807991cff9d9170c7d39d3d14985daca/src/Hangfire.SqlServer/SqlServerJobQueue.cs#L99), you'll see that it's not really a zero but instead a minimum of 50 milliseconds. I do not know what's the reasoning of allowing to set lower polling interval on their side.

What I see here, is that we only check if it's non-negative, meaning we could still allow DoS'ing the database with timespan like 0.00:00:00.0001, but at least it's not really a hidden value in the implementation, so it's up for the users of library to know what they're doing.

After writing the last paragraph, I really think there should rather be a hard limit on this value which throws at runtime if someone tries to set unreasonably low value, even if positive, but the _unreasonable_ part is highly debatable.

**Comment by frankhommers** [comment]
@azygis I agree with this. Setting it to Zero and using 50ms for real makes no sense in the SqlServerStorageOptions.
I think we could throw on that <50ms, what do you think?

**Comment by azygis** [comment]
@frankhommers
Sounds good to me. Though with that I suggest to also add xmldoc's on options properties, it would then potentially be visible in intellisense before getting exceptions at runtime. At least by people who sometimes read what intellisense shows.

**Comment by frankhommers** [comment]
@asadcr are you willing to make a PR for this?
