### ISSUE TITLE
Transient Runtime Error After upgrading to version 1.9.7: Failed to create background task; Collection was modified.

### ISSUE THREAD

**Issue by cescobargiraldo** [frankhommers/Hangfire.PostgreSql#251]
We recently upgraded our microservices to the latest Hangfire.PostgresSql (v.1.9.7) and we are now noticing a weird transient error that keeps popping up very often. The issue looks like this:

![image](https://user-images.githubusercontent.com/25250963/169407171-270aee64-71c6-4f83-940c-70366e2d4954.png)

The issue disappears if we re-queue the background task though, but it's unmanageable to keep manually re-queuing every failed task that appears during the day as they seem to appear more often under heavier loads.

Do you guys know what might be triggering this?

**Comment by frankhommers** [comment]
@Plasma Can you maybe confirm that PR 253 is solving this?

**Comment by Plasma** [comment]
Hi @frankhommers I've taken a look, I think there are a few things to discuss:

1. master currently has failing tests

2. PR #248 by @jhartmann123 fixes an issue where when transaction enlistment is enabled, it can cause prepared transactions, due to Enlist/Timezone being set on the connection string, which fails the query. That PR fixes that issue, but now the UTC value is not set on the Timezone of the connection string automatically when Enlistment is in use, and allowing non-UTC timezone can cause the problems documented by the PR that enforces the UTC timezone on the connection. I don't really know what to do here, as its broken behavior of Hangfire Postgres is using a query with non-UTC timezone setting, really we need to probably adjust all the columns to be UTC only in the first place so the connection string timezone is not relevant, but thats a much larger change.

3. This PR #253 has an unrelated change https://github.com/frankhommers/Hangfire.PostgreSql/pull/253/files#diff-66c1a61579c4273dc1c4cecf58942bc957c9bcb9bc6e508e069a288856d80d17R229 that is not appropriate (string check instead of using the Settings property), perhaps @cescobargiraldo could not compile properly because of the recent introduction of the C# 10 language usage of "namespace" declaration after the merge of PR #252 https://github.com/frankhommers/Hangfire.PostgreSql/pull/252/files#diff-fbcd17500da941bc0e6f1efa4e3bdede551557b2a184a5f5869cb6c51b50200eR24 as I ran into this issue too

Perhaps as a first step, to get back to a known good state:
1. Replace usage of `namespace x;` with `namespace x { ... }` for non-C# 10 language compatability (fix compile issue)
2. Move the connection string setup as per https://github.com/frankhommers/Hangfire.PostgreSql/pull/253/files#diff-66c1a61579c4273dc1c4cecf58942bc957c9bcb9bc6e508e069a288856d80d17R437 to constructor as suggested
3. For now, update my test that checks for UTC timezone being set (`Connection_Timezone_Is_Set_To_UTC_For_Npgsql6_Compatibility`) to not run when Enlistment is used (tests use this, though) so the test won't fail. This would mean we don't raise an error though that "Hey, your enlisted transaction may not be in UTC, this may break Hangfire with weird timestamps", but that would be a temporary solution before the columns are updated to be UTC (Npgsql driver really did a number on making these changes, breaking so many things subtly...)

**Comment by Plasma** [comment]
No worries, I've just put together #255 which the above changes

**Comment by cescobargiraldo** [comment]
Hi guys, I was off for some days and hadn't seen this.

I see, yes, I did think to myself that the fix to move it to the constructor was too easy to be good for a long-term solution.  Thanks for the info and help with this @Plasma.

Do we know when this will make it out there to a new nuget version?
