### ISSUE TITLE
How to resolve this issue

### ISSUE THREAD

**Issue by srikanthg508** [frankhommers/Hangfire.PostgreSql#263]
While accessing HangFire Dashboard i am facing below issue.
![image](https://user-images.githubusercontent.com/94897489/192196332-c4613ec3-f33b-462b-a292-84f4341d49e8.png).

I am using below nuget versions:

    1) .Net core 3.1
    2) Hangfire.Postgresql 1.8.6
    3) Hangfire.Postgresql.Npgsql5 1.9.9
    4) HangFire.AspNetCore 1.7.31.

Please help me to resolve this issue.

**Comment by azygis** [comment]
Your versions do not seem right. You cannot have both `Hangfire.PostgreSql` and `Hangfire.PostgreSql.Npgsql5` versions installed at the same time, and also two separate versions, unless they are conditional.

`PostgreSqlStorageOptions.PrepareSchemaIfNecessary` should be set to true (it's the default) when setting the storage on Hangfire.

**Comment by srikanthg508** [comment]
Thanks for your response. Present i set the PostgreSqlStorageOptions.PrepareSchemaIfNecessary=false because i am creating tables manually by  context.Database.Migrate() using Entity Framework.

**Comment by azygis** [comment]
Your entity framework instance is separate from hangfire, with a separate schema. Hangfire.PoatgreSql does not (and will not) use EF.

**Comment by srikanthg508** [comment]
Is there any possibility to resolve this issue without setting PostgreSqlStorageOptions.PrepareSchemaIfNecessary=true. Because 
i created the tables manually using migration for storage.

**Comment by azygis** [comment]
Sure, it's possible. As long as you create all the tables correctly (see [Scripts](https://github.com/frankhommers/Hangfire.PostgreSql/tree/master/src/Hangfire.PostgreSql/Scripts)), no exceptions would be thrown. However, I strongly advice against that since it's basically reinventing the wheel while adding a soft lock on the package version.

Why exactly are you creating the third party library tables as your own EF migrations?

**Comment by srikanthg508** [comment]
Thanks @azygis.It's working fine.
