### ISSUE TITLE
Unable to make it work with bit.io

### ISSUE THREAD

**Issue by ollie10** [frankhommers/Hangfire.PostgreSql#285]
Hello,

I'm trying to switch my Hangfire storage from Mongo to Postgres using this service [https://bit.io/]( https://bit.io/).
They provide 3 database with 3 GB space each for free, which for my use case is more than enough.

Anyway I'm stuck trying to connect to the database, any connection leads to an error which is my case is:

```
Hangfire.PostgreSql.PostgreSqlDistributedLockException: 'Could not place a lock on the resource 'hangfire:lock:recurring-job:xxxx': Lock timeout.'

Inner exception:
PostgresException: 42P01: relation "hangfire.lock" does not exist
```

What happens is, that just nothing is inserted in the DB nor any table being created.

It seems that it is unable to connect to the database, I tried in both ways, they tell to (as database name) the naming: **username/database_name** but in the case it doesn't work switch to **username.database_name**. In neither cases with no luck.

Any clue with what's happening? I tried the connection string formatted in various ways but it should just work with the one I see here:
[https://docs.bit.io/docs/using-bitio-with-c-and-net](https://docs.bit.io/docs/using-bitio-with-c-and-net)

`Host={bitHost};Username={bitUser};Password={bitApiKey};Database={bitDbName}`

Many thanks

**Comment by azygis** [comment]
Hello.

Can you show how you set up your hangfire instance/storage? Startup logs would also be good as these show whether the schema is getting installed at all.

Do you use EF by any chance with drop-recreate policy?

**Comment by ollie10** [comment]
Hello, many thanks, consider only that the same configuration works currently in Mongo in a production environment.

So I'm switching from:
 ```csharp
// CONFIGURING HANGFIRE
MongoUrlBuilder mongoUrlBuilder = new MongoUrlBuilder(Configuration.GetConnectionString("MongoHangfireConnectionString"));
MongoClient mongoClient = new MongoClient(mongoUrlBuilder.ToMongoUrl());

services.AddHangfire(configuration => configuration
	.SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
	.UseSimpleAssemblyNameTypeSerializer()
	.UseRecommendedSerializerSettings()
	.UseMongoStorage(mongoClient, mongoUrlBuilder.DatabaseName, new MongoStorageOptions
	{
		MigrationOptions = new MongoMigrationOptions { MigrationStrategy = new Hangfire.Mongo.Migration.Strategies.DropMongoMigrationStrategy(), BackupStrategy = new Hangfire.Mongo.Migration.Strategies.Backup.NoneMongoBackupStrategy() },
		JobExpirationCheckInterval = TimeSpan.FromMinutes(30),
		Prefix = "hangfire.mongo",
		CheckConnection = true
	})
```

To:

 ```csharp
services.AddHangfire(configuration => configuration
	.SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
	.UseSimpleAssemblyNameTypeSerializer()
	.UseRecommendedSerializerSettings()
	.UsePostgreSqlStorage(Configuration.GetConnectionString("PostGresHangfireConnectionString"))
);
```


This is the log from NLog, after that Error Position 13 and 30 will keep repeating infinitely in loop and web app won't start
Log published here (to not clutter the message) [https://logpaste.com/0mazlxDM](https://logpaste.com/0mazlxDM)

**Comment by azygis** [comment]
The relevant part is spit out at the very beginning:

> 2023-02-14 14:17:24.8624||ERROR|Hangfire.PostgreSql.PostgreSqlStorage|Error while executing install/upgrade Npgsql.PostgresException (0x80004005): 0A000: PL/pgSQL EXECUTE command is not supported

That's a limitation of bit.io.

At this particular moment it seems like it fails when creating the schema. You can try creating one yourself manually so the script doesn't try to do it for you. If that helps, you'll need to also adjust your schema according to the Install.v14.sql and Install.v16.sql manually, since those are using `EXECUTE` as well.

1. Let the startup run installer to v14, until it fails.
2. Do the steps in Install.v14.sql manually.
3. Update `hangfire.schema.version` to 14.
4. Let the startup run installer to v16, until it fails.
5. Do the steps in Install.v14.sql manually.
6. Update `hangfire.schema.version` to 16.

At this point the migration should now be done.

If that doesn't help, then... If you **must** use bit.io, my suggestion is to go through the whole [install script folder](https://github.com/frankhommers/Hangfire.PostgreSql/tree/master/src/Hangfire.PostgreSql/Scripts) and match your hangfire database and schema with what has been done in those scripts, and then disable the automatic schema updates by setting `PostgreSqlStorageOptions.PrepareSchemaIfNecessary` to `false`. Keep in mind that you'd need to track all the updates and make the necessary changes (if any) manually after every update of this package.

**Comment by ollie10** [comment]
Hello @azygis, I see your point, I tried to switch from a read/write user to an admin user (thinking maybe was a permission issue) but even the admin has the same problem. So I suppose I will just change provider and that's it for the moment, it seems they have a list of what they support and what not [https://docs.bit.io/docs/supported-sql](https://docs.bit.io/docs/supported-sql) but the execute command is not stated as far as I see.

Many thanks

**Comment by azygis** [comment]
Indeed, even though the `EXECUTE` command is not listed in either supported or unsupported lists, their error message says it isn't (and to refer to bit.io docs). I agree that switching providers may be a better option, but keep in mind hosted providers can also have a restricted use for `EXECUTE` as it can be used outside your database scope.

**Comment by ollie10** [comment]
Yes I saw their hint, anyway it should be clearly stated so developers should not waste time...
