### ISSUE TITLE
Counter table?

### ISSUE THREAD

**Issue by bherila** [frankhommers/Hangfire.PostgreSql#40]
The Counter table tends to grow very large for some reason. Can older items be purged or maybe we can use an ENUM value for the `key` field to condense the storage somewhat? Thoughts?

![image](https://cloud.githubusercontent.com/assets/1422004/17748802/e5a9bd9c-646f-11e6-84e8-4ae811caca6b.png)

Idea: 
- Upper box -> Convert to separate field
- Lower box -> Convert to `enum`

**Comment by frankhommers** [comment]
I made the data model to be almost the same as the SqlServer version. We could decide to move away from being the same. Look here: https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/Install.sql and search for [Counter].

We could also make a statetype table instead of an enum.

**Comment by frankhommers** [comment]
Is there still a need for this? Otherwise I am closing this...
