### ISSUE TITLE
BackgroundJob.Enqueue not work in TransactionScope

### ISSUE THREAD

**Issue by ficnar** [frankhommers/Hangfire.PostgreSql#93]
Using BackgroundJob.Enqueue inside TransactionScope throw exception „System.NotSupportedException: Nested/Concurrent transactions aren't supported.“
The reason is that Npgsql not supports Nested/Concurrent transactions.
Problem is in the method Hangfire.PostgreSql.WriteOnlyTransaction.Commit.
This method always beginning a new sql transaction.
The solution may be beginning new sql transaction only if Transaction.Current is null.

Or, do exists other solution for this problem?

Note:
I tested on the forked project ahydrax/Hangfire.PostgreSql.

**Comment by mantasaudickas** [comment]
Have you tried to set `Enlist=true` into your connection string?

**Comment by Recodify** [comment]
I am having this same problem.

```
using (var tran = new TransactionScope(TransactionScopeOption.Required, transactionOptions, TransactionScopeAsyncFlowOption.Enabled))
            {                
              Hangfire.BackgroundJob.Enqueue(() => new MyJob(service).Execute(null, data));
                  
              // DO SOMETHING THAT THROWS
             
              tran.Complete();
            }
```

And my connection string is: 

`server=127.0.0.1;uid=xxxx;pwd=xxxx;database=hangfire;enlist=true`

Yet the job still gets created

**Comment by frankhommers** [comment]
So this means that @vytautask's fix is not working properly?

**Comment by enetatt741** [comment]
Any progress on TransactionScope support?

**Comment by vytautask** [comment]
I need volunteers to test that :)
Do not feel confident just pushing it to the PROD in the current state...

**Comment by davidroth** [comment]
@vytautask I have created a new pull request which enables transaction scopes in a safe manner (behind a new flag):

https://github.com/frankhommers/Hangfire.PostgreSql/pull/137

**Comment by davidroth** [comment]
We are currently testing my [MR](https://github.com/frankhommers/Hangfire.PostgreSql/pull/137) in on of our apps. 
I have published a package containing the patch, so that others can test too:

https://dev.azure.com/fusonicgmbh/public-nuget/_packaging?_a=package&feed=github-forks&package=Hangfire.PostgreSql&protocolType=NuGet&version=1.6.2-Fusonic.1

`Install-Package Hangfire.PostgreSql -version 1.6.2-Fusonic.1`

So far, we are not seeing any issues.

**Comment by frankhommers** [comment]
@davidroth, @vytautask: So we should take David's fix and merge that instead of Vytautus' fix?

**Comment by davidroth** [comment]
@frankhommers 

I would recommend so, because my MR includes:

 - Additional unit tests for verifying the new behavior
 - An additional `EnableTransactionScopeEnlistment` boolean property. This allows users to explicitly enable this feature when needed. With this flag, we don`t break existing users which do not want implicit transaction scope enlistment. Otherwise this would be a breaking change.
- If scope enlistment is enabled, it adopts transaction isolation level from ambient transaction. Its important to re-use the same isolation level from the ambient transaction. Otherwise it would not work.

**Comment by vytautask** [comment]
Yeah, just merge it ;)
IMHO, David did a great job here.

**Comment by frankhommers** [comment]
OK! Merged it.

**Comment by davidroth** [comment]
@frankhommers Thanks for merging. When do you plan to publish an updated nuget package?

**Comment by davidroth** [comment]
Ping @frankhommers

**Comment by frankhommers** [comment]
https://github.com/frankhommers/Hangfire.PostgreSql/pull/137 got released.
